import { useState, useEffect, type CSSProperties, type FC, type ReactNode } from 'react'
import { ToolLogo } from './TechLogos'
import { hi } from './syntaxHighlight'
import type { CourseSlide, TeachingNote } from './TeachingNotes'
import { AMPHI } from './amphi'

const D1 = '#F4F7FB'
const D2 = '#FFFFFF'
const D3 = '#EEF2F7'
const D4 = '#CBD5E1'
const OW = '#0F172A'
const SUB = '#334155'
const MUTED = '#64748B'
const ORANGE = '#F97300'
const BLUE = '#2563EB'
const EMERALD = '#10B981'
const VIOLET = '#8B5CF6'
const RED = '#EF4444'
const AMBER = '#F59E0B'
const E_BG = '#0D1117'
const E_BORD = '#21262D'

const display: CSSProperties = { fontFamily: "'Syne', system-ui, sans-serif" }
const mono: CSSProperties = { fontFamily: "'JetBrains Mono', monospace" }

function isPrint() {
  return typeof document !== 'undefined' && document.documentElement.dataset.printing === '1'
}

function useReveal(delays: number[]) {
  const printing = isPrint()
  const [phase, setPhase] = useState(printing ? delays.length : 0)
  useEffect(() => {
    if (isPrint()) { setPhase(delays.length); return }
    const t = delays.map((ms, i) => setTimeout(() => setPhase(i + 1), ms))
    return () => t.forEach(clearTimeout)
  }, []) // eslint-disable-line react-hooks/exhaustive-deps
  return phase
}

function Fade({ show, children, className = '', style }: {
  show: boolean; children: ReactNode; className?: string; style?: CSSProperties
}) {
  if (isPrint() && !show) return null
  return (
    <div className={className} style={{
      ...style,
      opacity: show ? 1 : 0,
      transform: show ? 'translateY(0)' : 'translateY(10px)',
      transition: isPrint() ? 'none' : 'opacity 0.55s ease, transform 0.55s ease',
      pointerEvents: show ? 'auto' : 'none',
    }}>{children}</div>
  )
}

function note(n: TeachingNote): TeachingNote { return n }

/** Question orale + réponses cliquables + révélation */
function AskBlock({
  question,
  choices,
  reveal,
  onPick,
  picked,
}: {
  question: string
  choices: { id: string; label: string }[]
  reveal: ReactNode
  onPick: (id: string) => void
  picked: string | null
}) {
  const open = picked !== null || isPrint()
  return (
    <div className="rounded-2xl p-5" style={{ background: D2, border: `3px solid ${ORANGE}` }}>
      <p className="mono font-black mb-2" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
        À VOUS — RÉPONDEZ
      </p>
      <p className="font-black mb-4 leading-tight" style={{ ...display, fontSize: AMPHI.slogan, color: OW }}>{question}</p>
      <div className="flex flex-wrap gap-3 mb-4">
        {choices.map(c => (
          <button
            key={c.id}
            type="button"
            onClick={() => onPick(c.id)}
            className="px-5 py-3 rounded-xl mono font-black"
            style={{
              ...mono, fontSize: AMPHI.btn,
              background: picked === c.id ? ORANGE : D3,
              color: picked === c.id ? '#fff' : OW,
              border: `3px solid ${picked === c.id ? ORANGE : OW}`,
              cursor: 'pointer',
            }}
          >
            {c.label}
          </button>
        ))}
      </div>
      {open && (
        <div className="rounded-xl px-5 py-4" style={{ background: ORANGE + '18', border: `3px solid ${ORANGE}` }}>
          {reveal}
        </div>
      )}
    </div>
  )
}

function Slogan({ children, color = ORANGE }: { children: ReactNode; color?: string }) {
  return (
    <p className="font-black leading-tight tracking-tight" style={{ ...display, fontSize: 'clamp(32px, 3.8vw, 48px)', color, letterSpacing: '-0.03em' }}>
      {children}
    </p>
  )
}

// ─── 1. Pourquoi programmer en 2026 ───────────────────────────────────────
function SlideWhyProgram2026() {
  const phase = useReveal([300, 900, 1800, 2800, 4000, 5200, 6500])
  const [vote, setVote] = useState<string | null>(isPrint() ? 'b' : null)

  const aiItems = [
    'génère du code en secondes',
    'explique un algorithme',
    'propose des corrections',
    'écrit des tests',
    'accélère le boilerplate',
  ]
  const humanItems = [
    'comprend le VRAI besoin',
    'modélise le problème',
    'choisit l’architecture',
    'vérifie que c’est juste',
    'assume la responsabilité',
  ]

  return (
    <div className="w-full h-full relative overflow-hidden flex flex-col px-12 py-8" style={{ background: D1 }}>
      <div className="absolute inset-0 pointer-events-none overflow-hidden opacity-[0.07] mono select-none">
        {Array.from({ length: 10 }).map((_, i) => (
          <div key={i} style={{
            ...mono, position: 'absolute', left: `${(i * 11) % 88}%`, top: `${6 + i * 9}%`,
            fontSize: 20, color: OW, whiteSpace: 'nowrap',
          }}>
            {['// generated by AI', 'TODO: verify', 'public class…', 'assertTrue(…)', 'SecurityException'][i % 5]}
          </div>
        ))}
      </div>

      <p className="mono font-black tracking-widest mb-2 relative z-10" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.18em' }}>
        QUESTION DU SEMESTRE
      </p>
      <h2 className="font-black relative z-10 mb-4 leading-none"
        style={{ ...display, fontSize: 'clamp(40px, 4.8vw, 56px)', color: OW, letterSpacing: '-0.035em', maxWidth: 1100 }}>
        UNE IA PEUT ÉCRIRE DU CODE.<br />
        <span style={{ color: ORANGE }}>ALORS… POURQUOI VOUS ?</span>
      </h2>

      <Fade show={phase >= 1} className="relative z-10 mb-4">
        <p className="mono font-black" style={{ ...mono, color: BLUE, fontSize: 24, letterSpacing: '0.06em' }}>
          GÉNÉRER DU CODE ≠ CRÉER UN LOGICIEL.
        </p>
      </Fade>

      <div className="flex gap-6 flex-1 relative z-10 min-h-0">
        <Fade show={phase >= 2} className="flex-1 rounded-2xl p-5 flex flex-col"
          style={{ background: D2, border: `4px solid ${BLUE}` }}>
          <p className="mono font-black mb-3" style={{ ...mono, color: BLUE, fontSize: 22, letterSpacing: '0.1em' }}>
            L’IA FAIT (VITE)
          </p>
          {aiItems.map((t, i) => (
            <Fade key={t} show={phase >= 2 + Math.min(i, 1)}>
              <p className="mono mb-2 font-black" style={{ ...mono, color: OW, fontSize: 22 }}>› {t}</p>
            </Fade>
          ))}
          <Fade show={phase >= 3} className="mt-auto pt-3">
            <div className="rounded-xl px-4 py-3 mono font-black" style={{ ...mono, background: AMBER + '28', border: `3px solid ${AMBER}`, color: '#92400E', fontSize: 20 }}>
              ⚠ TAG OBLIGATOIRE : « À VÉRIFIER »
            </div>
          </Fade>
        </Fade>

        <div className="flex flex-col items-center justify-center shrink-0 w-16">
          <Fade show={phase >= 2}>
            <p className="mono font-black text-center leading-tight" style={{ ...mono, color: ORANGE, fontSize: 20, letterSpacing: '0.06em' }}>
              COLLÉGUES<br />PAS<br />RIVAUX
            </p>
          </Fade>
        </div>

        <Fade show={phase >= 3} className="flex-1 rounded-2xl p-5 flex flex-col"
          style={{ background: D2, border: `4px solid ${ORANGE}` }}>
          <p className="mono font-black mb-3" style={{ ...mono, color: ORANGE, fontSize: 22, letterSpacing: '0.1em' }}>
            VOUS DEVEZ (SINON ÉCHEC)
          </p>
          {humanItems.map(t => (
            <p key={t} className="mono mb-2 font-black" style={{ ...mono, color: OW, fontSize: 22 }}>› {t}</p>
          ))}
        </Fade>
      </div>

      <Fade show={phase >= 5} className="mt-3 relative z-10">
        <AskBlock
          question="Si l’IA écrit 100 % de votre TP… qu’avez-vous appris ?"
          choices={[
            { id: 'a', label: 'Coder plus vite' },
            { id: 'b', label: 'Rien — sauf si je comprends' },
            { id: 'c', label: 'Écrire des prompts' },
          ]}
          picked={vote}
          onPick={setVote}
          reveal={
            <p className="font-black leading-snug" style={{ ...display, fontSize: 24, color: OW }}>
              À retenir : <span style={{ color: ORANGE }}>« L’IA accélère. Elle ne remplace pas la compréhension. »</span>
            </p>
          }
        />
      </Fade>
    </div>
  )
}

// ─── 2. Qui fait quoi ─────────────────────────────────────────────────────
const TASKS = [
  { id: 'm1', label: 'Écrire une méthode simple' },
  { id: 'm2', label: 'Comprendre le besoin client' },
  { id: 'm3', label: 'Générer un squelette de classe' },
  { id: 'm4', label: 'Choisir les responsabilités' },
  { id: 'm5', label: 'Proposer un test' },
  { id: 'm6', label: 'Vérifier qu’un résultat est correct' },
  { id: 'm7', label: 'Règle métier ambiguë' },
  { id: 'm8', label: 'Refactoriser' },
  { id: 'm9', label: 'Détecter une incohérence de conception' },
  { id: 'm10', label: 'Générer de la documentation' },
] as const

type Bucket = 'pool' | 'ai' | 'human' | 'collab'

function SlideWhoDoesWhat() {
  const [sel, setSel] = useState<string | null>(null)
  const [place, setPlace] = useState<Record<string, Bucket>>(() =>
    Object.fromEntries(TASKS.map(t => [t.id, 'pool' as Bucket]))
  )
  const [done, setDone] = useState(isPrint())
  const [hook, setHook] = useState<string | null>(isPrint() ? 'c' : null)

  const move = (bucket: Bucket) => {
    if (!sel) return
    setPlace(p => ({ ...p, [sel]: bucket }))
    setSel(null)
  }

  const cols: { key: Bucket; title: string; color: string; hint: string }[] = [
    { key: 'ai', title: 'IA PEUT AIDER', color: BLUE, hint: 'vitesse' },
    { key: 'human', title: 'HUMAIN DOIT DÉCIDER', color: ORANGE, hint: 'responsabilité' },
    { key: 'collab', title: 'COLLABORATION', color: EMERALD, hint: 'le plus souvent' },
  ]

  const placed = TASKS.filter(t => place[t.id] !== 'pool').length

  return (
    <div className="w-full h-full flex flex-col px-8 py-6" style={{ background: D1 }}>
      <div className="flex items-end justify-between gap-4 mb-2">
        <div>
          <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
            MINI-JEU · PAS DE RÉPONSE BINAIRE
          </p>
          <h2 className="font-black leading-none" style={{ ...display, fontSize: AMPHI.title, color: OW, letterSpacing: '-0.03em' }}>
            QUI PORTE LA RESPONSABILITÉ ?
          </h2>
        </div>
        <p className="mono font-black" style={{ ...mono, color: OW, fontSize: 22 }}>
          {placed}/{TASKS.length}
        </p>
      </div>

      <p className="mb-3 font-black leading-snug" style={{ color: OW, fontSize: 22 }}>
        Cliquez une carte → une colonne.&nbsp;
        <span style={{ color: ORANGE }}>« L’IA peut » ≠ « L’IA décide seule »</span>
      </p>

      <div className="flex flex-wrap gap-2.5 mb-3">
        {TASKS.filter(t => place[t.id] === 'pool').map(t => (
          <button key={t.id} type="button" onClick={() => setSel(t.id)}
            className="mono px-4 py-2.5 rounded-xl text-left font-black"
            style={{
              ...mono, fontSize: AMPHI.card,
              background: sel === t.id ? ORANGE : D2,
              border: `3px solid ${sel === t.id ? ORANGE : OW}`,
              color: sel === t.id ? '#fff' : OW,
              cursor: 'pointer',
            }}>
            {t.label}
          </button>
        ))}
      </div>

      <div className="flex gap-4 flex-1 min-h-0 mb-3">
        {cols.map(c => (
          <button key={c.key} type="button" onClick={() => move(c.key)}
            className="flex-1 rounded-2xl p-4 flex flex-col text-left"
            style={{
              background: D2,
              border: `4px solid ${c.color}`,
              cursor: sel ? 'pointer' : 'default',
              boxShadow: sel ? `0 0 0 4px ${c.color}33` : undefined,
            }}>
            <p className="mono font-black leading-tight" style={{ ...mono, color: c.color, fontSize: 22, letterSpacing: '0.04em' }}>
              {c.title}
            </p>
            <p className="mono font-black mb-3" style={{ ...mono, color: MUTED, fontSize: 16 }}>{c.hint}</p>
            <div className="flex flex-col gap-2 flex-1 overflow-auto">
              {TASKS.filter(t => place[t.id] === c.key).map(t => (
                <div key={t.id} className="mono px-3 py-2.5 rounded-xl font-black"
                  style={{
                    ...mono, fontSize: 20,
                    background: c.color + '22',
                    color: OW,
                    border: `2px solid ${c.color}`,
                  }}
                  onClick={e => { e.stopPropagation(); setSel(t.id) }}>
                  {t.label}
                </div>
              ))}
            </div>
          </button>
        ))}
      </div>

      <div className="flex items-stretch gap-3 shrink-0">
        <button type="button" onClick={() => setDone(true)}
          className="px-7 py-4 rounded-xl mono font-black shrink-0"
          style={{ ...mono, background: ORANGE, color: '#fff', fontSize: 22, border: `3px solid ${ORANGE}` }}>
          VALIDER
        </button>
        {(done || isPrint()) ? (
          <div className="flex-1 rounded-xl px-5 py-3 flex flex-col justify-center" style={{ background: OW }}>
            <p className="font-black leading-tight" style={{ ...display, color: '#fff', fontSize: 26 }}>
              Compétence 2026 : <span style={{ color: ORANGE }}>COMPRENDRE + GUIDER + VÉRIFIER</span>
            </p>
            <p className="font-bold mt-1" style={{ color: '#E2E8F0', fontSize: 18 }}>
              Si vous ne savez pas juger la sortie de l’IA, vous n’êtes pas développeur — vous êtes opérateur de copier-coller.
            </p>
          </div>
        ) : (
          <div className="flex-1 min-w-0">
            <AskBlock
              question="Qui signe le code en production ?"
              choices={[
                { id: 'a', label: 'L’IA' },
                { id: 'b', label: 'Le prof' },
                { id: 'c', label: 'MOI' },
              ]}
              picked={hook}
              onPick={setHook}
              reveal={
                <p className="font-black" style={{ color: OW, fontSize: 24 }}>
                  VOUS. Toujours. L’IA n’a pas de badge d’employé.
                </p>
              }
            />
          </div>
        )}
      </div>
    </div>
  )
}

// ─── 3. IA = copilote ─────────────────────────────────────────────────────
function SlideAiCopilot() {
  const phase = useReveal([400, 1100, 2000, 3000, 4200, 5500, 7000])
  const [picked, setPicked] = useState<string | null>(null)
  const [stepQ, setStepQ] = useState<string | null>(isPrint() ? 'x' : null)
  const showSurprise = picked !== null || phase >= 7 || isPrint()

  const versions = [
    { id: 'A', title: 'Notes', attrs: ['nom', 'matricule', 'moyenne'], c: BLUE },
    { id: 'B', title: 'Bibliothèque', attrs: ['nom', 'nombreLivresEmpruntes'], c: VIOLET },
    { id: 'C', title: 'Présence', attrs: ['nom', 'nombreAbsences'], c: EMERALD },
  ]

  return (
    <div className="w-full h-full flex flex-col px-11 py-8" style={{ background: D1 }}>
      <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.16em' }}>
        RÈGLE D’OR
      </p>
      <h2 className="font-black mb-2 leading-none" style={{ ...display, fontSize: 48, color: OW }}>
        L’IA EST COPILOTE. <span style={{ color: ORANGE }}>PAS PILOTE.</span>
      </h2>
      <Fade show={phase >= 1}>
        <p className="mono font-black mb-4" style={{ ...mono, color: RED, fontSize: 24, letterSpacing: '0.04em' }}>
          PROMPT CORRECT ≠ SOLUTION CORRECTE
        </p>
      </Fade>

      <div className="flex gap-3 mb-4">
        {[
          { n: '01', t: 'VOUS', d: 'Je comprends. Je modélise. Je décide.', c: ORANGE },
          { n: '02', t: 'IA', d: 'Elle propose. Elle génère. Elle explique.', c: BLUE },
          { n: '03', t: 'VOUS', d: 'Je vérifie. Je teste. Je signe.', c: EMERALD },
        ].map((b, i) => (
          <Fade key={b.n} show={phase >= i + 1} className="flex-1 rounded-2xl p-4"
            style={{ background: D2, border: `4px solid ${b.c}` }}>
            <p className="mono font-black" style={{ ...mono, color: b.c, fontSize: 26 }}>{b.n}</p>
            <p className="font-black" style={{ color: OW, fontSize: 26 }}>{b.t}</p>
            <p className="font-bold" style={{ color: SUB, fontSize: 18, marginTop: 4 }}>{b.d}</p>
          </Fade>
        ))}
      </div>

      <Fade show={phase >= 4} className="mb-4">
        <AskBlock
          question="Si je ne comprends pas le problème… puis-je faire confiance à l’IA ?"
          choices={[
            { id: 'x', label: 'Non' },
            { id: 'y', label: 'Oui si le prompt est long' },
            { id: 'z', label: 'Oui si ça compile' },
          ]}
          picked={stepQ}
          onPick={setStepQ}
          reveal={
            <p className="font-black" style={{ fontSize: 18, color: OW }}>
              NON. <span style={{ color: ORANGE }}>Sans modèle mental, vous ne détectez pas l’erreur.</span> Vous validez à l’aveugle.
            </p>
          }
        />
      </Fade>

      <Fade show={phase >= 5} className="flex-1 flex flex-col min-h-0">
        <p className="mono mb-2 font-bold" style={{ ...mono, color: MUTED, fontSize: 18 }}>
          EXPÉRIENCE — Prompt flou : « Crée une classe Etudiant en Java. »
        </p>
        <div className="flex gap-3 flex-1 min-h-0">
          {versions.map(v => (
            <button key={v.id} type="button" onClick={() => setPicked(v.id)}
              className="flex-1 rounded-2xl p-4 text-left"
              style={{
                background: D2,
                border: `2px solid ${picked === v.id || showSurprise ? v.c : D4}`,
                cursor: 'pointer',
                boxShadow: picked === v.id ? `0 0 0 3px ${v.c}33` : undefined,
              }}>
              <p className="mono font-black mb-1" style={{ ...mono, color: v.c, fontSize: 22 }}>Version {v.id}</p>
              <p className="font-black mb-2" style={{ color: MUTED, fontSize: 16 }}>{v.title}</p>
              {v.attrs.map(a => (
                <p key={a} className="mono font-black" style={{ ...mono, color: OW, fontSize: 22 }}>{a}</p>
              ))}
            </button>
          ))}
        </div>
        <p className="mt-3 font-black" style={{ ...display, fontSize: 26, color: OW }}>
          LAQUELLE EST « LA » BONNE ?
          {showSurprise && (
            <span style={{ color: ORANGE }}> — SURPRISE : LES TROIS. TOUT DÉPEND DU PROBLÈME.</span>
          )}
        </p>
        {showSurprise && (
          <p className="mono font-black mt-1" style={{ ...mono, color: BLUE, fontSize: 20 }}>
            UNE ENTITÉ RÉELLE → PLUSIEURS MODÈLES POSSIBLES.
          </p>
        )}
      </Fade>
    </div>
  )
}

// ─── 4. Pourquoi la POO ───────────────────────────────────────────────────
function SlideWhyOopSense() {
  const phase = useReveal([500, 1400, 2600, 4000, 5400])
  const [q, setQ] = useState<string | null>(isPrint() ? 'b' : null)
  const sizes = ['20', '100', '1 000', '10 000', '100 000']
  const blocks = ['Utilisateur', 'Commande', 'Produit', 'Paiement', 'Facture', 'Stock']

  return (
    <div className="w-full h-full flex flex-col px-11 py-8" style={{ background: D1 }}>
      <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
        POURQUOI LA POO — SANS HÉRITAGE ENCORE
      </p>
      <h2 className="font-black mb-4 leading-none" style={{ ...display, fontSize: 42, color: OW }}>
        QUAND LE CODE GROSSIT… <span style={{ color: RED }}>QUI RANGÉ ?</span>
      </h2>

      <Fade show={phase >= 1} className="flex gap-2 mb-5">
        {sizes.map((n, i) => (
          <div key={n} className="rounded-xl px-4 py-3 mono font-black flex-1 text-center"
            style={{
              ...mono, fontSize: 18,
              background: phase >= 2 && i >= 3 ? RED + '18' : D3,
              color: phase >= 2 && i >= 3 ? RED : SUB,
              border: `1.5px solid ${phase >= 2 && i >= 3 ? RED : D4}`,
            }}>
            {n}<br /><span style={{ fontSize: 20, fontWeight: 600 }}>lignes</span>
          </div>
        ))}
      </Fade>

      <Fade show={phase >= 2 && phase < 4} className="mb-4">
        <Slogan color={OW}>COMMENT ORGANISER SANS DEVENIR FOU ?</Slogan>
        <div className="h-24 mt-4 rounded-2xl relative overflow-hidden" style={{ background: D3, border: `2px dashed ${RED}` }}>
          {Array.from({ length: 20 }).map((_, i) => (
            <div key={i} className="absolute rounded" style={{
              left: `${(i * 19) % 92}%`, top: `${(i * 27) % 65}%`,
              width: 36 + (i % 5) * 10, height: 12 + (i % 3) * 7,
              background: i % 2 ? ORANGE + '55' : BLUE + '55',
            }} />
          ))}
          <p className="absolute inset-0 flex items-center justify-center font-black" style={{ ...display, color: RED, fontSize: 28 }}>
            CHAOS
          </p>
        </div>
      </Fade>

      <Fade show={phase >= 4} className="flex-1 flex flex-col">
        <p className="mono font-black mb-3" style={{ ...mono, color: EMERALD, fontSize: 18, letterSpacing: '0.12em' }}>
          MÊME SYSTÈME — RESPONSABILITÉS CLAIRES
        </p>
        <div className="flex flex-wrap gap-2 mb-4">
          {blocks.map(b => (
            <div key={b} className="rounded-xl px-4 py-3 font-black"
              style={{ background: D2, border: `3px solid ${BLUE}`, color: OW, fontSize: 22, fontWeight: 900 }}>
              {b}
            </div>
          ))}
        </div>
        <p className="font-black mb-3" style={{ ...display, fontSize: 24, color: OW }}>
          La POO = organiser autour de <span style={{ color: ORANGE }}>qui fait quoi</span>.
        </p>
        <div className="grid grid-cols-2 gap-2 mb-4">
          {[
            'Qui possède cette donnée ?',
            'Qui exécute cette action ?',
            'Qui a le droit d’y accéder ?',
            'Comment les parties collaborent-elles ?',
          ].map(qq => (
            <p key={qq} className="mono font-bold rounded-xl px-3 py-2.5" style={{ ...mono, background: D3, color: OW, fontSize: 20, fontWeight: 900 }}>
              ? {qq}
            </p>
          ))}
        </div>
        <AskBlock
          question="La POO sert surtout à… ?"
          choices={[
            { id: 'a', label: 'Écrire moins de lignes' },
            { id: 'b', label: 'Structurer responsabilités' },
            { id: 'c', label: 'Impressionner le jury' },
          ]}
          picked={q}
          onPick={setQ}
          reveal={
            <p className="font-black" style={{ fontSize: 18, color: OW }}>
              Structurer. <span style={{ color: ORANGE }}>Moins de chaos = plus de maîtrise.</span>
            </p>
          }
        />
      </Fade>
    </div>
  )
}

// ─── 5. Pourquoi Java ─────────────────────────────────────────────────────
function SlideWhyJavaConcepts() {
  const phase = useReveal([400, 1200, 2400, 3600, 4800])
  const [q, setQ] = useState<string | null>(isPrint() ? 'b' : null)
  const concepts = [
    'types', 'classes', 'objets', 'attributs', 'méthodes',
    'constructeurs', 'encapsulation', 'interfaces', 'exceptions',
  ]
  const langs = ['C#', 'Kotlin', 'TypeScript', 'Python', 'autres…']

  return (
    <div className="w-full h-full flex flex-col items-center px-12 py-8 relative overflow-hidden" style={{ background: D1 }}>
      <p className="mono font-black tracking-widest mb-2" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
        POURQUOI JAVA — PAS « PARCE QUE C’EST POPULAIRE »
      </p>
      <h2 className="font-black mb-2 text-center leading-none" style={{ ...display, fontSize: 40, color: OW }}>
        JAVA NOUS FORCE À VOIR CLAIREMENT
      </h2>
      <Fade show={phase >= 1}>
        <p className="mono font-black text-center mb-6" style={{ ...mono, color: BLUE, fontSize: 18 }}>
          CE QUI EST FLOU DANS LA TÊTE DEVIENT VISIBLE DANS LE CODE.
        </p>
      </Fade>

      <div className="relative mb-6" style={{ width: 560, height: 280 }}>
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-10">
          <ToolLogo kind="java" size={96} />
        </div>
        {concepts.map((c, i) => {
          const angle = (i / concepts.length) * Math.PI * 2 - Math.PI / 2
          const r = 118
          const x = 280 + Math.cos(angle) * r
          const y = 140 + Math.sin(angle) * r
          return (
            <Fade key={c} show={phase >= 2}>
              <span className="absolute mono font-black px-2.5 py-1 rounded-lg"
                style={{
                  ...mono, left: x, top: y, transform: 'translate(-50%, -50%)',
                  fontSize: 18, background: D2, border: `3px solid ${ORANGE}`, color: OW, fontWeight: 900,
                }}>
                {c}
              </span>
            </Fade>
          )
        })}
      </div>

      <Fade show={phase >= 3} className="text-center mb-2">
        <Slogan color={OW}>NOUS N’APPRENONS PAS « QUE » JAVA.</Slogan>
      </Fade>
      <Fade show={phase >= 4} className="text-center mb-4">
        <Slogan>NOUS APPRENONS À CONCEVOIR — AVEC JAVA COMME OUTIL.</Slogan>
      </Fade>
      <Fade show={phase >= 5} className="w-full max-w-3xl">
        <div className="flex gap-2 justify-center mb-4 flex-wrap">
          {langs.map(l => (
            <span key={l} className="mono px-3 py-1.5 rounded-full font-black"
              style={{ ...mono, background: BLUE + '14', color: BLUE, border: `2px solid ${BLUE}`, fontSize: 18, fontWeight: 900 }}>
              {l}
            </span>
          ))}
        </div>
        <AskBlock
          question="Dans 5 ans, qu’emportez-vous de ce cours ?"
          choices={[
            { id: 'a', label: 'La syntaxe Java exacte' },
            { id: 'b', label: 'La façon de modéliser' },
            { id: 'c', label: 'Les logos des outils' },
          ]}
          picked={q}
          onPick={setQ}
          reveal={
            <p className="font-black" style={{ fontSize: 18, color: OW }}>
              La conception. <span style={{ color: ORANGE }}>Les concepts voyagent. La syntaxe change.</span>
            </p>
          }
        />
      </Fade>
    </div>
  )
}

// ─── 6. 2000 lignes ───────────────────────────────────────────────────────
function SlideAi2000Lines() {
  const phase = useReveal([300, 1000, 2200, 3600, 5000, 6400])
  const [count, setCount] = useState(isPrint() ? 2000 : 10)
  const [q, setQ] = useState<string | null>(isPrint() ? 'c' : null)
  useEffect(() => {
    if (isPrint()) return
    if (phase < 1) return
    let n = 10
    const id = setInterval(() => {
      n = Math.min(2000, n + (n < 200 ? 18 : n < 800 ? 45 : 90))
      setCount(n)
      if (n >= 2000) clearInterval(id)
    }, 35)
    return () => clearInterval(id)
  }, [phase])

  const verbs = ['COMPRENDRE', 'CONCEVOIR', 'ÉVALUER', 'TESTER', 'AMÉLIORER']
  const dark = phase >= 3

  return (
    <div className="w-full h-full flex flex-col items-center justify-center px-12 relative overflow-hidden"
      style={{ background: dark ? '#0B1220' : D1, transition: 'background 0.7s' }}>
      <Fade show={phase >= 1} className="text-center mb-4">
        <p className="mono font-black tabular-nums leading-none"
          style={{ ...mono, fontSize: 110, color: dark ? ORANGE : OW }}>
          {count.toLocaleString('fr-FR')}
        </p>
        <p className="mono font-black" style={{ ...mono, color: dark ? '#94A3B8' : MUTED, fontSize: 18, letterSpacing: '0.2em' }}>
          LIGNES · QUELQUES SECONDES
        </p>
      </Fade>

      <Fade show={phase >= 2} className="text-center mb-6">
        <p className="font-black leading-tight" style={{ ...display, fontSize: 34, color: dark ? '#F8FAFC' : OW }}>
          L’IA PEUT BOMBARDER DE CODE.
        </p>
      </Fade>

      <Fade show={phase >= 4} className="text-center mb-6 max-w-4xl">
        <p className="font-black leading-tight" style={{ ...display, fontSize: 36, color: ORANGE }}>
          2 000 LIGNES MAL CONÇUES<br />= 2 000 PROBLÈMES À MAINTENIR.
        </p>
      </Fade>

      <Fade show={phase >= 5} className="text-center mb-6">
        <p style={{ color: dark ? '#94A3B8' : SUB, fontSize: 20, marginBottom: 14, fontWeight: 700 }}>
          Votre valeur n’est PAS votre vitesse de frappe.
        </p>
        <div className="flex gap-2 flex-wrap justify-center mb-6">
          {verbs.map(v => (
            <span key={v} className="mono font-black px-3 py-2 rounded-xl"
              style={{ ...mono, background: ORANGE + '28', color: ORANGE, fontSize: 20, letterSpacing: '0.08em' }}>
              {v}
            </span>
          ))}
        </div>
        <div className="max-w-xl mx-auto">
          <AskBlock
            question="Que préférez-vous livrer ?"
            choices={[
              { id: 'a', label: '2000 lignes floues' },
              { id: 'b', label: '200 lignes solides' },
              { id: 'c', label: 'Le bon modèle d’abord' },
            ]}
            picked={q}
            onPick={setQ}
            reveal={
              <p className="font-black" style={{ fontSize: 18, color: OW }}>
                Le modèle d’abord. <span style={{ color: ORANGE }}>Puis le code — humain ou IA.</span>
              </p>
            }
          />
        </div>
      </Fade>
    </div>
  )
}

// ─── 7. Mini défi BankAccount ─────────────────────────────────────────────
function SlideAiMiniChallenge() {
  const [choice, setChoice] = useState<'yes' | 'no' | 'idk' | null>(isPrint() ? 'no' : null)
  const [flaw, setFlaw] = useState<string | null>(null)
  const reveal = choice !== null || isPrint()

  const flaws = [
    { id: 'neg', label: 'montant négatif ?' },
    { id: 'over', label: 'retrait &gt; solde ?' },
    { id: 'pub', label: 'balance public ?' },
    { id: 'biz', label: 'règles métier ?' },
  ]

  return (
    <div className="w-full h-full flex gap-8 px-11 py-8" style={{ background: D1 }}>
      <div className="flex-1 flex flex-col min-w-0">
        <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
          DÉFI AMPHI — 90 SECONDES
        </p>
        <h2 className="font-black mb-2 leading-none" style={{ ...display, fontSize: 32, color: OW }}>
          BATTEZ L’IA… <span style={{ color: ORANGE }}>SUR LE JUGEMENT.</span>
        </h2>
        <p className="mono mb-3 font-bold" style={{ ...mono, color: MUTED, fontSize: 18 }}>
          Prompt IA : « Crée une classe BankAccount en Java. » → voici SA réponse.
        </p>
        <div className="flex-1 rounded-xl overflow-hidden" style={{ border: `1px solid ${E_BORD}`, background: E_BG }}>
          <div className="px-4 py-2 mono text-xs font-bold" style={{ ...mono, color: AMBER, borderBottom: `1px solid ${E_BORD}` }}>
            ⚠ compile… mais est-ce correct ?
          </div>
          <div className="p-5 mono" style={{ ...mono, fontSize: 19, lineHeight: 1.6, color: '#D4D4D4' }}>
            {`class BankAccount {
    public double balance;

    void withdraw(double amount) {
        balance -= amount;
    }
}`.split('\n').map((line, i) => (
              <div key={i} className="whitespace-pre" dangerouslySetInnerHTML={{ __html: hi(line) || '&nbsp;' }} />
            ))}
          </div>
        </div>
      </div>

      <div className="w-[400px] flex flex-col justify-center shrink-0">
        <p className="font-black mb-3 leading-tight" style={{ ...display, fontSize: 26, color: OW }}>
          Ce code compile.<br />
          <span style={{ color: ORANGE }}>Est-il forcément correct ?</span>
        </p>
        <div className="flex flex-col gap-2 mb-4">
          {([
            ['yes', 'Oui — ça compile'],
            ['no', 'Non — trop naïf'],
            ['idk', 'Je ne sais pas encore'],
          ] as const).map(([k, label]) => (
            <button key={k} type="button" onClick={() => setChoice(k)}
              className="px-4 py-3 rounded-xl mono font-black text-left"
              style={{
                ...mono, fontSize: 22,
                background: choice === k ? ORANGE : D2,
                color: choice === k ? '#fff' : OW,
                border: `3px solid ${choice === k ? ORANGE : OW}`,
              }}>
              {label}
            </button>
          ))}
        </div>
        {reveal && (
          <div className="rounded-2xl p-4" style={{ background: OW }}>
            <p className="font-black mb-3" style={{ ...display, color: ORANGE, fontSize: 22 }}>
              COMPILER ≠ ÊTRE CORRECT
            </p>
            <p className="mb-3" style={{ color: '#CBD5E1', fontSize: 20 }}>
              Cliquez chaque faille que vous voyez :
            </p>
            <div className="flex flex-col gap-1.5 mb-3">
              {flaws.map(f => (
                <button key={f.id} type="button" onClick={() => setFlaw(f.id)}
                  className="mono text-left px-3 py-2 rounded-lg font-bold"
                  style={{
                    ...mono, fontSize: 20,
                    background: flaw === f.id ? ORANGE + '33' : '#1E293B',
                    color: flaw === f.id ? ORANGE : '#E2E8F0',
                    border: `2px solid ${flaw === f.id ? ORANGE : '#64748B'}`,
                  }}
                  dangerouslySetInnerHTML={{ __html: `› ${f.label}` }}
                />
              ))}
            </div>
            <p className="font-black" style={{ color: '#fff', fontSize: 16 }}>
              Le développeur sait ce que le programme <span style={{ color: ORANGE }}>DEVRAIT</span> faire — avant de faire confiance à une IA.
            </p>
          </div>
        )}
      </div>
    </div>
  )
}

// ─── 8. Méthode de travail ────────────────────────────────────────────────
function SlideHowWeWork() {
  const phase = useReveal([350, 800, 1250, 1700, 2150, 2600, 3050, 3800, 4800])
  const [q, setQ] = useState<string | null>(isPrint() ? 'a' : null)
  const steps = [
    'COMPRENDRE', 'MODÉLISER', 'CODER', 'TESTER',
    'DEMANDER À L\'IA', 'VÉRIFIER', 'AMÉLIORER',
  ]

  return (
    <div className="w-full h-full flex flex-col px-11 py-8" style={{ background: D1 }}>
      <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
        CONTRAT DE TRAVAIL — CETTE ANNÉE
      </p>
      <h2 className="font-black mb-2 leading-none" style={{ ...display, fontSize: 38, color: OW }}>
        L’IA ARRIVE <span style={{ color: ORANGE }}>APRÈS</span> LA PENSÉE.
      </h2>
      <p className="mono font-black mb-6" style={{ ...mono, color: RED, fontSize: 16 }}>
        JAMAIS : IA d’abord → cerveau ensuite.
      </p>

      <div className="flex flex-wrap gap-2 mb-8">
        {steps.map((s, i) => (
          <Fade key={s} show={phase >= i + 1} className="flex items-center gap-1.5">
            <div className="rounded-xl px-3 py-2.5 mono font-black"
              style={{
                ...mono, fontSize: 18, letterSpacing: '0.04em',
                background: i === 4 ? BLUE + '18' : i === 0 ? ORANGE + '18' : D2,
                border: `3px solid ${i === 0 ? ORANGE : i === 4 ? BLUE : OW}`,
                color: i === 0 ? ORANGE : OW,
              }}>
              {i + 1}. {s}
            </div>
            {i < steps.length - 1 && <span style={{ color: MUTED, fontWeight: 900 }}>→</span>}
          </Fade>
        ))}
      </div>

      <Fade show={phase >= 8} className="flex gap-4 mb-5">
        <div className="flex-1 rounded-2xl p-5" style={{ background: RED + '10', border: `2px solid ${RED}` }}>
          <p className="mono font-black mb-2" style={{ ...mono, color: RED, fontSize: 20, letterSpacing: '0.1em' }}>INTERDIT</p>
          <p className="font-black leading-snug" style={{ ...display, color: OW, fontSize: 22 }}>
            Copier → Coller → Exécuter → Espérer
          </p>
          <p style={{ color: SUB, fontSize: 20, marginTop: 8 }}>Surnom : méthode « roulette russe »</p>
        </div>
        <div className="flex-1 rounded-2xl p-5" style={{ background: EMERALD + '10', border: `2px solid ${EMERALD}` }}>
          <p className="mono font-black mb-2" style={{ ...mono, color: EMERALD, fontSize: 20, letterSpacing: '0.1em' }}>ATTENDU</p>
          <p className="font-black leading-snug" style={{ ...display, color: OW, fontSize: 22 }}>
            Comprendre → Demander → Analyser → Tester → Corriger
          </p>
          <p style={{ color: SUB, fontSize: 20, marginTop: 8 }}>Surnom : méthode « développeur »</p>
        </div>
      </Fade>

      <Fade show={phase >= 9}>
        <AskBlock
          question="Où placez-vous l’IA dans VOTRE pipeline ce semestre ?"
          choices={[
            { id: 'a', label: 'Après comprendre + tenter' },
            { id: 'b', label: 'Avant de réfléchir' },
            { id: 'c', label: 'À la place du examen' },
          ]}
          picked={q}
          onPick={setQ}
          reveal={
            <p className="font-black" style={{ fontSize: 18, color: OW }}>
              Après. <span style={{ color: ORANGE }}>Sinon vous entraînez votre dépendance, pas votre métier.</span>
            </p>
          }
        />
      </Fade>
    </div>
  )
}

// ─── 9. Charte IA ─────────────────────────────────────────────────────────
function SlideAiCharter() {
  const [q, setQ] = useState<string | null>(isPrint() ? 'b' : null)
  const ok = [
    'Demander une explication',
    'Demander un exemple',
    'Générer une première version',
    'Demander des cas de test',
    'Comparer 2–3 solutions',
    'Déboguer avec l’IA',
  ]
  const no = [
    'Copier sans comprendre',
    'Rendre un code inexplicable',
    'Accepter sans tester',
  ]

  return (
    <div className="w-full h-full flex flex-col px-11 py-8" style={{ background: D1 }}>
      <p className="mono font-black tracking-widest mb-1" style={{ ...mono, color: ORANGE, fontSize: AMPHI.kicker, letterSpacing: '0.14em' }}>
        CHARTE — PAS UNE PUNITION, UN STANDARD PRO
      </p>
      <h2 className="font-black mb-5 leading-none" style={{ ...display, fontSize: 34, color: OW }}>
        L’IA EST AUTORISÉE.<br />
        <span style={{ color: ORANGE }}>VOUS RESTEZ LE DÉVELOPPEUR RESPONSABLE.</span>
      </h2>

      <div className="flex gap-5 flex-1 min-h-0 mb-4">
        <div className="flex-1 rounded-2xl p-5" style={{ background: D2, border: `4px solid ${EMERALD}` }}>
          <p className="mono font-black mb-3" style={{ ...mono, color: EMERALD, fontSize: 20, letterSpacing: '0.1em' }}>✓ AUTORISÉ</p>
          {ok.map(t => (
            <p key={t} className="font-black" style={{ color: OW, fontSize: 22, marginBottom: 10 }}>✓ {t}</p>
          ))}
        </div>
        <div className="flex-1 rounded-2xl p-5" style={{ background: D2, border: `4px solid ${RED}` }}>
          <p className="mono font-black mb-3" style={{ ...mono, color: RED, fontSize: 20, letterSpacing: '0.1em' }}>✗ INTERDIT</p>
          {no.map(t => (
            <p key={t} className="font-black" style={{ color: OW, fontSize: 22, marginBottom: 10 }}>✗ {t}</p>
          ))}
        </div>
      </div>

      <div className="rounded-2xl px-6 py-4 mb-4" style={{ background: OW }}>
        <p className="font-black leading-tight" style={{ ...display, fontSize: 22, color: '#fff' }}>
          RÈGLE DU COURS — À MÉMORISER :<br />
          <span style={{ color: ORANGE }}>« Si vous utilisez une ligne, vous devez pouvoir l’expliquer. »</span>
        </p>
      </div>

      <AskBlock
        question="On vous demande : « Expliquez cette ligne. » Que faites-vous ?"
        choices={[
          { id: 'a', label: 'Je relis le prompt IA' },
          { id: 'b', label: 'Je l’explique moi-même' },
          { id: 'c', label: 'Je change de sujet' },
        ]}
        picked={q}
        onPick={setQ}
        reveal={
          <p className="font-black" style={{ fontSize: 18, color: OW }}>
            Vous l’expliquez. <span style={{ color: ORANGE }}>Sinon ce n’était pas VOTRE code.</span>
          </p>
        }
      />
    </div>
  )
}

// ─── 10. Finale ───────────────────────────────────────────────────────────
function SlideIntroFinale() {
  const phase = useReveal([500, 1600, 3000, 4500, 6000])
  const [q, setQ] = useState<string | null>(isPrint() ? 'b' : null)

  return (
    <div className="w-full h-full flex flex-col items-center justify-center px-14 text-center" style={{ background: D1 }}>
      <Fade show={phase >= 1}>
        <p className="mono font-black mb-4" style={{ ...mono, color: ORANGE, fontSize: 18, letterSpacing: '0.2em' }}>
          PHRASE FINALE — PREMIÈRE SÉANCE
        </p>
        <p className="font-black leading-tight mb-6" style={{ ...display, fontSize: 34, color: OW, maxWidth: 980 }}>
          Votre objectif n’est PAS d’écrire du code plus vite qu’une IA.
        </p>
      </Fade>
      <Fade show={phase >= 2}>
        <p className="font-black leading-tight mb-8" style={{ ...display, fontSize: 30, color: SUB, maxWidth: 980 }}>
          Votre objectif : savoir <span style={{ color: ORANGE }}>QUEL</span> code écrire,
          <span style={{ color: ORANGE }}> POURQUOI</span>,
          et comment <span style={{ color: ORANGE }}>VÉRIFIER</span> qu’il est correct.
        </p>
      </Fade>
      <Fade show={phase >= 3} className="w-full max-w-2xl mb-8 text-left">
        <AskBlock
          question="Première brique de la POO — on attaque quoi ?"
          choices={[
            { id: 'a', label: 'Les boucles for' },
            { id: 'b', label: 'Classe vs objet' },
            { id: 'c', label: 'Spring Boot' },
          ]}
          picked={q}
          onPick={setQ}
          reveal={
            <p className="font-black" style={{ fontSize: 18, color: OW }}>
              Classe vs objet. <span style={{ color: ORANGE }}>Le reste s’appuie dessus.</span>
            </p>
          }
        />
      </Fade>
      <Fade show={phase >= 4}>
        <div className="w-16 h-1.5 rounded mb-5 mx-auto" style={{ background: ORANGE }} />
        <p className="font-black" style={{ ...display, fontSize: 48, color: ORANGE }}>
          CLASSE OU OBJET ?
        </p>
      </Fade>
    </div>
  )
}

// ─── Export registries ────────────────────────────────────────────────────
export const AI_INTRO_PRE: CourseSlide[] = [
  {
    component: SlideWhyProgram2026,
    chapter: 'Contexte IA',
    id: 'why-2026',
    notes: note({
      title: 'Pourquoi apprendre à programmer en 2026 ?',
      teachingGoal: 'Ancrer : générer ≠ comprendre ; responsabilité humaine.',
      speakerNotes: 'Faire voter sur la question « qu’avez-vous appris ? ». Insister sur le tag À VÉRIFIER. Phrase murale : GÉNÉRER ≠ CRÉER UN LOGICIEL.',
      question: 'Si l’IA écrit 100 % du TP, qu’avez-vous appris ?',
      expectedAnswer: 'Rien de durable sans compréhension et vérification.',
      transition: 'Mini-jeu : qui porte la responsabilité ?',
      estimatedMinutes: 5,
    }),
  },
  {
    component: SlideWhoDoesWhat,
    chapter: 'Contexte IA',
    id: 'who-does-what',
    notes: note({
      title: 'Qui porte la responsabilité ?',
      teachingGoal: 'Collaboration oui, délégation aveugle non.',
      speakerNotes: 'Laisser classer. Relancer : « l’IA peut » ≠ « l’IA décide ». Phrase : COMPRENDRE + GUIDER + VÉRIFIER.',
      question: 'Qui signe le code en production ?',
      expectedAnswer: 'L’humain / le développeur.',
      transition: 'Copilote, pas pilote + expérience Etudiant.',
      estimatedMinutes: 6,
    }),
  },
  {
    component: SlideAiCopilot,
    chapter: 'Contexte IA',
    id: 'ai-copilot',
    notes: note({
      title: 'IA = copilote',
      teachingGoal: 'Prompt flou → modèles multiples ; tout dépend du problème.',
      speakerNotes: 'Effet surprise sur A/B/C. Faire dire à voix haute : UNE ENTITÉ → PLUSIEURS MODÈLES.',
      question: 'Sans comprendre le problème, peut-on faire confiance à l’IA ?',
      expectedAnswer: 'Non.',
      transition: 'Regardez autour de vous — le monde réel.',
      estimatedMinutes: 5,
    }),
  },
]

export const AI_INTRO_MID: CourseSlide[] = [
  {
    component: SlideWhyOopSense,
    chapter: 'Contexte IA',
    id: 'why-oop-sense',
    notes: note({
      title: 'Pourquoi la POO ?',
      teachingGoal: 'POO = responsabilités claires quand le code grossit.',
      speakerNotes: 'Montrer le chaos 100k lignes puis les blocs. Quatre questions orales.',
      question: 'La POO sert surtout à… ?',
      expectedAnswer: 'Structurer les responsabilités.',
      transition: 'Pourquoi Java pour apprendre ça.',
      estimatedMinutes: 4,
    }),
  },
  {
    component: SlideWhyJavaConcepts,
    chapter: 'Contexte IA',
    id: 'why-java-concepts',
    notes: note({
      title: 'Pourquoi Java ?',
      teachingGoal: 'Java force la clarté ; concepts transférables.',
      speakerNotes: 'Phrase : ce qui est flou dans la tête devient visible dans le code.',
      question: 'Dans 5 ans, qu’emportez-vous ?',
      expectedAnswer: 'La façon de modéliser / concevoir.',
      transition: '2000 lignes mal conçues.',
      estimatedMinutes: 3,
    }),
  },
  {
    component: SlideAi2000Lines,
    chapter: 'Contexte IA',
    id: 'ai-2000',
    notes: note({
      title: '2000 lignes mal conçues',
      teachingGoal: 'Volume ≠ qualité ; valeur = jugement.',
      speakerNotes: 'Silence après le slogan orange. Vote : modèle d’abord.',
      question: 'Que préférez-vous livrer ?',
      expectedAnswer: 'Le bon modèle d’abord.',
      transition: 'Défi BankAccount.',
      estimatedMinutes: 3,
    }),
  },
  {
    component: SlideAiMiniChallenge,
    chapter: 'Contexte IA',
    id: 'ai-challenge',
    notes: note({
      title: 'BankAccount imparfait',
      teachingGoal: 'COMPILER ≠ CORRECT ; failles métier.',
      speakerNotes: '90 secondes. Faire cliquer les failles. Ne pas spoiler trop tôt.',
      question: 'Ce code compile. Est-il correct ?',
      expectedAnswer: 'Non — validations, encapsulation, règles métier manquent.',
      transition: 'Méthode de travail.',
      estimatedMinutes: 5,
    }),
  },
  {
    component: SlideHowWeWork,
    chapter: 'Contexte IA',
    id: 'how-we-work',
    notes: note({
      title: 'Méthode de travail',
      teachingGoal: 'IA après la pensée ; interdire roulette russe.',
      speakerNotes: 'Pointer l’étape 5. Contraster INTERDIT / ATTENDU.',
      question: 'Où placez-vous l’IA ?',
      expectedAnswer: 'Après comprendre + tenter.',
      transition: 'Charte.',
      estimatedMinutes: 3,
    }),
  },
  {
    component: SlideAiCharter,
    chapter: 'Contexte IA',
    id: 'ai-charter',
    notes: note({
      title: 'Charte IA',
      teachingGoal: 'Standard pro : expliquer chaque ligne utilisée.',
      speakerNotes: 'Faire répéter la règle du cours à voix haute.',
      question: 'On demande d’expliquer une ligne — que faites-vous ?',
      expectedAnswer: 'Je l’explique moi-même.',
      transition: 'Phrase finale → classe ou objet.',
      estimatedMinutes: 3,
    }),
  },
  {
    component: SlideIntroFinale,
    chapter: 'Contexte IA',
    id: 'intro-finale',
    notes: note({
      title: 'Objectif du développeur',
      teachingGoal: 'Mémoriser QUEL / POURQUOI / VÉRIFIER → classe vs objet.',
      speakerNotes: 'Lire lentement. Vote sur la première brique.',
      question: 'Première brique ?',
      expectedAnswer: 'Classe vs objet.',
      transition: 'Ouverture monde réel / classe vs objet.',
      estimatedMinutes: 2,
    }),
  },
]

export const AI_INTRO_ALL: CourseSlide[] = [...AI_INTRO_PRE, ...AI_INTRO_MID]
