/**
 * Notes enseignant — une fiche par slide, dans l’ordre du cours.
 * Utilisé par le mode enseignant (N) et l’export téléchargeable.
 */
import type { TeachingNote } from './TeachingNotes'

export type SlideNoteEntry = TeachingNote & {
  id: string
  chapter: string
  slideNumber?: number
}

function n(
  id: string,
  chapter: string,
  title: string,
  teachingGoal: string,
  speakerNotes: string,
  question: string,
  expectedAnswer: string,
  transition: string,
  estimatedMinutes: number,
): SlideNoteEntry {
  return { id, chapter, title, teachingGoal, speakerNotes, question, expectedAnswer, transition, estimatedMinutes }
}

/** Catalogue ordonné — doit rester aligné avec le registre SLIDES de App.tsx */
export const ALL_SLIDE_NOTES: SlideNoteEntry[] = [
  // ── Accueil ────────────────────────────────────────────────────────────
  n('title', 'Accueil', 'Page de présentation',
    'Accrocher le public et présenter le cadre du cours POO Java (Licence GLSI 2).',
    'Saluer, présenter le semestre, rappeler que le cours est interactif (pas un PowerPoint). Annoncer le fil : IA → monde réel → abstraction → classe → objet.',
    'Que savez-vous déjà de la POO ou de Java ?',
    'Réponses variées : certains ont vu du C, Python, notions de classe.',
    'Entrer dans le contexte 2026 : pourquoi apprendre à programmer à l’ère de l’IA.',
    2),

  // ── Contexte IA (PRE) ──────────────────────────────────────────────────
  n('why-2026', 'Contexte IA', 'Pourquoi apprendre à programmer en 2026 ?',
    'Ancrer : générer ≠ comprendre ; l’humain porte la responsabilité.',
    'Faire voter. Phrase murale : GÉNÉRER DU CODE ≠ CRÉER UN LOGICIEL. Insister sur « À VÉRIFIER ».',
    'Si l’IA écrit 100 % du TP, qu’avez-vous appris ?',
    'Rien de durable sans compréhension et vérification.',
    'Mini-jeu : qui porte la responsabilité ?',
    5),
  n('who-does-what', 'Contexte IA', 'Qui porte la responsabilité ?',
    'Collaboration oui, délégation aveugle non. Compétence = comprendre + guider + vérifier.',
    'Laisser classer. Relancer : « l’IA peut » ≠ « l’IA décide ». Qui signe en production ?',
    'Qui signe le code en production ?',
    'MOI / le développeur — jamais l’IA seule.',
    'Copilote + expérience Etudiant multi-modèles.',
    6),
  n('ai-copilot', 'Contexte IA', 'IA = copilote, pas pilote',
    'PROMPT CORRECT ≠ SOLUTION CORRECTE ; une entité → plusieurs modèles.',
    'Vote confiance IA. Surprise A/B/C. Faire répéter : UNE ENTITÉ → PLUSIEURS MODÈLES.',
    'Sans comprendre le problème, peut-on faire confiance à l’IA ?',
    'Non.',
    'Monde réel : regardez autour de vous.',
    5),

  // ── Ouverture EARLY ────────────────────────────────────────────────────
  n('open-01-look', 'Ouverture', 'Regardez autour de vous',
    'Ancrer : entité = état + comportement ; tout attend d’être modélisé.',
    'Faire cliquer et nommer à voix haute. Phrase : ÉTAT + COMPORTEMENT.',
    'Pour une Voiture : donnez 2 états et 2 comportements.',
    'Ex. couleur/vitesse ; démarrer/freiner.',
    'Comment représenter ce monde dans un programme ?',
    3),
  n('open-02-represent', 'Ouverture', 'Comment représenter ce monde ?',
    'Ordinateur = données + instructions ; pas de modèle → pas de programme fiable.',
    'Révéler « EN CRÉANT UN MODÈLE ». Vote : sans modèle on tape au hasard.',
    'Comment transformer une entité réelle en représentation programmable ?',
    'En créant un modèle.',
    'Abstraction : filtrer l’utile.',
    4),
  n('open-03-abstraction', 'Ouverture', 'Abstraction',
    'Garder l’utile, jeter le reste ; une entité ≠ un seul modèle.',
    'Changer Notes/Biblio/Présence. Faire répéter le slogan.',
    'Avons-nous besoin de la couleur des yeux pour les notes ?',
    'Non.',
    'Formaliser le modèle Étudiant.',
    4),
  n('open-04-model', 'Ouverture', 'Réalité → Abstraction → Modèle',
    'MODÈLE ≠ personne réelle ; contrat de l’application.',
    'Phrase : MODÈLE ≠ SARRA ≠ AHMED ≠ LINA.',
    'Un modèle est-il égal à une personne ?',
    'Non.',
    'Traduction en classe Java.',
    3),
  n('open-05-java', 'Ouverture', 'Modèle → Classe Java',
    'Montrer la traduction attributs/méthodes → champs/méthodes Java (y compris sInscrire).',
    'Suivre la synchro gauche/droite. Récapituler la chaîne MONDE → ABSTRACTION → MODÈLE → CLASSE.',
    'Que devient « nom » en Java ?',
    'String nom; (type + nom de champ).',
    'Pourquoi organiser un gros système avec la POO ?',
    4),

  // ── Contexte IA (MID) ──────────────────────────────────────────────────
  n('why-oop-sense', 'Contexte IA', 'Pourquoi la POO ?',
    'POO = responsabilités claires quand le code grossit.',
    'Montrer chaos puis blocs. Vote : structurer responsabilités.',
    'La POO sert surtout à… ?',
    'Structurer les responsabilités.',
    'Pourquoi Java pour apprendre ça.',
    4),
  n('why-java-concepts', 'Contexte IA', 'Pourquoi Java ? (concepts)',
    'Java comme langage de travail pour apprendre à concevoir.',
    'Insister sur le transfert : C#, Kotlin, TypeScript, Python…',
    'Apprend-on « Java » ou « la conception » ?',
    'Les deux : Java rend les concepts explicites.',
    'Et si l’IA génère 2000 lignes ?',
    3),
  n('ai-2000', 'Contexte IA', '2000 lignes mal conçues',
    'Séparer volume de code et qualité de conception.',
    'Laisser un silence après le grand message. Faire apparaître COMPRENDRE → AMÉLIORER.',
    'Qu’est-ce qui donne de la valeur à un développeur ?',
    'Comprendre, concevoir, évaluer, tester, améliorer.',
    'Mini-défi : un code qui compile mais…',
    3),
  n('ai-challenge', 'Contexte IA', 'Mini-défi BankAccount',
    'COMPILER ≠ CORRECT ; faire émerger règles métier et encapsulation.',
    'Ne pas spoiler le solde négatif. Faire voter Oui / Non / Je ne sais pas.',
    'Que manque-t-il à withdraw ?',
    'Validations, accès contrôlé au solde, règles métier.',
    'Notre méthode de travail cette année.',
    4),
  n('how-we-work', 'Contexte IA', 'Comment nous allons travailler',
    'Ancrer le pipeline : comprendre avant l’IA.',
    'Repérer l’étape IA après compréhension/test. Opposer INTERDIT vs ATTENDU.',
    'Où place-t-on l’IA dans le processus ?',
    'Après compréhension et première tentative, jamais avant.',
    'Charte d’usage de l’IA.',
    2),
  n('ai-charter', 'Contexte IA', 'Charte d’utilisation de l’IA',
    'Clarifier les règles sans punition : expliquer = obligation.',
    'Présenter comme contrat moral du semestre. Ton positif.',
    'Que devez-vous pouvoir faire avec chaque ligne utilisée ?',
    'L’expliquer.',
    'Phrase finale puis transition classe / objet.',
    2),
  n('intro-finale', 'Contexte IA', 'Objectif du développeur',
    'Clore le storytelling intro avant CLASSE vs OBJET.',
    'Lire à voix haute la phrase finale. Annoncer la première brique.',
    'Quelle est la première brique ?',
    'Comprendre classe et objet.',
    'Une classe peut créer plusieurs objets.',
    2),

  // ── Ouverture LATE ─────────────────────────────────────────────────────
  n('open-06-class-not-object', 'Ouverture', 'Classe ≠ objet',
    'Une classe → plusieurs objets ; plan vs instance.',
    'Vote « trois classes ? » puis NON. Phrase : CLASSE = PLAN · OBJET = INSTANCE.',
    'Faut-il trois classes pour Sarra, Ahmed, Lina ?',
    'Non.',
    'new et objets vivants.',
    3),
  n('open-07-alive', 'Ouverture', 'Le modèle prend vie',
    'Relier new Etudiant() à la création d’une instance vivante.',
    'Montrer que chaque objet a sa propre identité / état.',
    'Que fait l’opérateur new ?',
    'Il crée un nouvel objet (instance) en mémoire.',
    'État et comportement sur un objet concret.',
    3),
  n('open-08-state-behavior', 'Ouverture', 'État et comportement',
    'Renforcer le duo attributs (état) / méthodes (comportement).',
    'Faire nommer pour un objet choisi dans la salle.',
    'Donnez un état et un comportement pour un Smartphone.',
    'Ex. batterie / appeler(), charger().',
    'Les objets collaborent dans un système.',
    3),
  n('open-09-collaborate', 'Ouverture', 'Les objets collaborent',
    'Un système = objets qui s’envoient des messages / appellent des méthodes.',
    'Relier Étudiant–Cours–Enseignant sans entrer dans UML avancé.',
    'Un objet travaille-t-il tout seul dans une vraie application ?',
    'Non : collaboration entre responsabilités.',
    'Mini-défi : modéliser une Voiture.',
    3),
  n('open-10-car', 'Ouverture', 'Défi Voiture',
    'Faire pratiquer état + comportement sur un exemple simple.',
    'Laisser proposer attributs/méthodes avant de corriger.',
    'Quels attributs et méthodes pour Voiture ?',
    'couleur, vitesse… demarrer(), accelerer(), freiner()…',
    'Pourquoi Java pour formaliser cela ?',
    3),
  n('open-11-why-java', 'Ouverture', 'Pourquoi Java ? (ouverture)',
    'Renforcer le choix de Java comme langage pédagogique.',
    'Lien avec portable, typé, OOP — sans jargon excessif.',
    'Citez un avantage de Java pour débuter la POO.',
    'Types explicites, classes obligatoires, vaste écosystème…',
    'Promesse du cours / transition chapitre 01.',
    2),
  n('open-12-promise', 'Ouverture', 'Promesse du cours',
    'Clore l’ouverture : Comprendre · Modéliser · Coder.',
    'Motiver pour le chapitre Introduction à Java.',
    'Que retiendrez-vous de cette ouverture en une phrase ?',
    'On abstrait le réel en modèle, puis en classe, pour créer des objets.',
    'Chapitre 01 — Introduction à Java.',
    2),

  // ── 01 Introduction ────────────────────────────────────────────────────
  n('ch1-opener', '01 Introduction', 'Chapitre 01 — Introduction à Java',
    'Ouvrir le chapitre technique : du source à l’exécution.',
    'Annoncer le plan : pourquoi Java, JVM, outils, premier programme, types.',
    'Qu’espérez-vous apprendre dans ce chapitre ?',
    'Écrire / exécuter un programme, comprendre JDK/JVM…',
    'Pourquoi Java (angle technique / historique).',
    1),
  n('ch1-why-java', '01 Introduction', 'Pourquoi Java ?',
    'Lister les forces : portable, OOP, typé, concurrent, sécurisé.',
    'Ne pas survoler : un exemple concret par mot-clé si possible.',
    'Que signifie « portable » pour Java ?',
    'Write once, run anywhere via la JVM / bytecode.',
    'Un peu d’histoire pour contextualiser.',
    3),
  n('ch1-history', '01 Introduction', 'Histoire de Java',
    'Situer Oak → Java, Sun → Oracle, évolution des versions.',
    'Rester léger : dates clés et intention du langage.',
    'Pourquoi Java a-t-il été créé ?',
    'Portabilité, réseau, simplicité relative vs C++…',
    'L’ADN / principes du langage.',
    2),
  n('ch1-dna', '01 Introduction', 'ADN de Java',
    'Ancrer les principes fondateurs (simplicité, robustesse, portabilité…).',
    'Relier chaque principe à une conséquence concrète pour l’étudiant.',
    'Quel principe justifie le typage fort ?',
    'Robustesse / détection précoce d’erreurs.',
    'Write once, run anywhere.',
    2),
  n('ch1-write-once', '01 Introduction', 'Write once, run anywhere',
    'Expliquer source → bytecode → JVM sur chaque OS.',
    'Schéma mental clair avant d’entrer dans l’architecture.',
    'Le .class est-il du code machine natif ?',
    'Non : bytecode interprété/compilé par la JVM.',
    'Écosystème Java.',
    2),
  n('ch1-ecosystem', '01 Introduction', 'Écosystème Java',
    'Montrer que Java ≠ seulement le langage : libs, outils, communauté.',
    'Éviter de surcharger : 4–5 piliers max.',
    'Citez un élément de l’écosystème hors langage.',
    'Maven/Gradle, Spring, JUnit, IDE…',
    'Éditions SE / EE / ME.',
    2),
  n('ch1-editions', '01 Introduction', 'Éditions Java (SE, EE, ME)',
    'Clarifier SE (ce cours), EE (entreprise), ME (embarqué/historique).',
    'Insister : on travaille en Java SE.',
    'Quelle édition pour ce cours GLSI ?',
    'Java SE.',
    'Pipeline de compilation / exécution.',
    2),
  n('ch1-pipeline', '01 Introduction', 'Pipeline source → exécution',
    'Visualiser : .java → javac → .class → java (JVM).',
    'Faire répéter le pipeline à voix haute.',
    'Quel outil produit le fichier .class ?',
    'Le compilateur javac.',
    'Architecture JVM / JDK.',
    3),
  n('ch1-architecture', '01 Introduction', 'Architecture Java (JDK / JRE / JVM)',
    'Distinguer JDK (développement), JRE (exécution), JVM (moteur).',
    'Schéma : JDK ⊃ JRE ⊃ JVM. Aujourd’hui on installe surtout le JDK.',
    'Avez-vous besoin du JDK pour seulement exécuter ?',
    'Historiquement JRE suffisait ; en pratique on installe le JDK.',
    'Chaîne d’outils concrète.',
    3),
  n('ch1-toolchain', '01 Introduction', 'Toolchain Java',
    'Présenter JDK, compilateur, runtime, IDE — logos réels.',
    'Lier chaque outil à une étape du pipeline.',
    'Que fait IntelliJ dans cette chaîne ?',
    'Édition, compilation, exécution, débogage — confort.',
    'Environnement de développement.',
    3),
  n('ch1-devenv', '01 Introduction', 'Environnement de développement',
    'Guider l’installation / organisation du poste étudiant.',
    'Vérifier que chacun sait où est le JDK et comment lancer un projet.',
    'Comment vérifier que java est installé ?',
    'java -version / javac -version dans un terminal.',
    'Prêt à coder.',
    3),
  n('ch1-ready', '01 Introduction', 'Prêt à coder',
    'Motivation : premier programme, checklist mentale.',
    'Rassurer : on va lire le code ligne à ligne.',
    'Êtes-vous prêts à écrire votre premier main ?',
    'Oui — avec structure class + main.',
    'Premier programme Java.',
    1),
  n('ch1-first-program', '01 Introduction', 'Premier programme Java',
    'Lire public class, main, System.out — sans magie.',
    'Faire annoter oralement chaque mot-clé important.',
    'Pourquoi main est-il static ?',
    'Appelé sans créer d’instance de la classe de démarrage.',
    'Identificateurs.',
    4),
  n('ch1-identifiers', '01 Introduction', 'Identificateurs',
    'Règles de nommage : lettres, chiffres, _, $ ; pas de mot-clé ; camelCase.',
    'Montrer des contre-exemples invalides.',
    '1etudiant est-il un identifiant valide ?',
    'Non : ne peut pas commencer par un chiffre.',
    'Commentaires.',
    2),
  n('ch1-comments', '01 Introduction', 'Commentaires',
    '//, /* */, /** */ — rôles (doc vs explication).',
    'Rappeler : un bon code se commente avec parcimonie.',
    'À quoi sert /** */ ?',
    'Javadoc / documentation d’API.',
    'Types primitifs.',
    2),
  n('ch1-primitives', '01 Introduction', 'Types primitifs',
    'byte short int long float double char boolean — familles.',
    'Insister sur int/double/boolean pour débuter ; taille de int.',
    'Quelle différence entre int et Integer ?',
    'int = primitif ; Integer = objet wrapper (plus tard).',
    'Casting.',
    3),
  n('ch1-casting', '01 Introduction', 'Casting',
    'Conversion implicite (élargissement) vs explicite (rétrécissement).',
    'Montrer perte d’information possible (double → int).',
    'Faut-il un cast pour int → long ?',
    'Non (élargissement sûr). Oui pour long → int.',
    'Défi casting.',
    3),
  n('ch1-cast-challenge', '01 Introduction', 'Défi casting',
    'Faire prédire le résultat avant d’exécuter mentalement.',
    'Laisser voter, puis expliquer.',
    'Que vaut (int) 3.9 ?',
    '3 (troncature, pas arrondi).',
    'Récap chapitre 01.',
    2),
  n('ch1-recap', '01 Introduction', 'Récapitulatif chapitre 01',
    'Synthétiser pipeline, outils, premier programme, types.',
    'Quiz oral rapide 3 questions.',
    'Citez les 3 étapes source → exécution.',
    '.java → javac → .class → JVM.',
    'Transition vers classes & objets.',
    2),

  // ── Transition / Ch2 ───────────────────────────────────────────────────
  n('transition', 'Transition', 'Transition vers les classes & objets',
    'Relier chapitre 01 à la POO concrète.',
    'Rappeler le fil intro : modèle → classe → objets.',
    'Qu’allons-nous construire maintenant ?',
    'Des classes et des objets Java.',
    'Ouverture chapitre 02.',
    1),
  n('ch2-opener', '02 Classes & Objets', 'Chapitre 02 — Classes & Objets',
    'Ouvrir le cœur de la POO en Java.',
    'Annoncer piliers, classe vs objet, constructeurs, this, String, static, encapsulation.',
    'Quelle différence intuitive entre classe et objet ?',
    'Classe = modèle / plan ; objet = instance concrète.',
    'Piliers de la POO (aperçu).',
    1),
  n('ch2-pillars', '02 Classes & Objets', 'Piliers de la POO',
    'Présenter encapsulation, héritage, polymorphisme, abstraction — sans tout détailler.',
    'Dire clairement : ce chapitre approfondit surtout classe/objet/encapsulation.',
    'Quel pilier cache les détails internes ?',
    'Encapsulation (et abstraction).',
    'Partir du problème avant le code.',
    3),
  n('ch2-problem-first', '02 Classes & Objets', 'Le problème d’abord',
    'Renforcer : comprendre le besoin avant d’écrire la classe.',
    'Rejouer le réflexe anti « coder trop vite » / anti copier-coller IA.',
    'Que fait-on avant d’ouvrir l’éditeur ?',
    'Comprendre et modéliser.',
    'Classe vs objet (formel).',
    2),
  n('ch2-class-vs-object', '02 Classes & Objets', 'Classe vs objet',
    'Formaliser en Java : class Etudiant vs new Etudiant().',
    'Utiliser analogie plan / maison ou moule / gâteau.',
    'Combien d’objets une classe peut-elle créer ?',
    'Autant que nécessaire (mémoire permettant).',
    'Anatomie d’une classe.',
    3),
  n('ch2-anatomy', '02 Classes & Objets', 'Anatomie d’une classe',
    'Champs, constructeurs, méthodes — repères visuels.',
    'Faire annoter un squelette au tableau.',
    'Où déclarer l’état d’un objet ?',
    'Dans les attributs / champs de la classe.',
    'Création d’objet.',
    3),
  n('ch2-object-creation', '02 Classes & Objets', 'Création d’objet',
    'Syntaxe Type nom = new Type(...) ;',
    'Distinguer déclaration de référence et création.',
    'Que contient la variable e1 après Etudiant e1 = new Etudiant() ?',
    'Une référence vers l’objet, pas « l’objet lui-même » au sens valeur.',
    'Hero new.',
    2),
  n('ch2-new-hero', '02 Classes & Objets', 'Le mot-clé new',
    'new alloue l’objet et appelle le constructeur.',
    'Insister sur le lien new ↔ constructeur.',
    'new appelle-t-il toujours un constructeur ?',
    'Oui (explicite ou défaut si présent).',
    'Références.',
    2),
  n('ch2-references', '02 Classes & Objets', 'Références',
    'Variable référence vs objet en mémoire (heap).',
    'Dessiner deux flèches possibles.',
    'Deux variables peuvent-elles pointer le même objet ?',
    'Oui.',
    'Deux références.',
    3),
  n('ch2-two-refs', '02 Classes & Objets', 'Deux références, un objet',
    'Montrer aliasing : modifier via r1 visible via r2.',
    'Préparer le piège du défi suivant.',
    'Si e2 = e1, combien d’objets ?',
    'Un seul objet, deux références.',
    'Défi références.',
    2),
  n('ch2-ref-challenge', '02 Classes & Objets', 'Défi références',
    'Faire prédire l’affichage après aliasing / réaffectation.',
    'Laisser voter avant la révélation.',
    'Après e2 = e1 puis e2.nom = "Lina", que vaut e1.nom ?',
    'Lina (même objet), sauf si nouvel objet a été créé entre-temps.',
    'Constructeurs (hero).',
    3),
  n('ch2-ctor-hero', '02 Classes & Objets', 'Rôle du constructeur',
    'Initialiser l’état à la création — invariant de départ.',
    'Comparer objet non initialisé vs construit proprement.',
    'Peut-on appeler un constructeur comme une méthode normale ?',
    'Non : via new (ou this/super dans d’autres contextes).',
    'Constructeurs en détail.',
    2),
  n('ch2-constructors', '02 Classes & Objets', 'Constructeurs',
    'Même nom que la classe, pas de type de retour.',
    'Montrer constructeur par défaut vs explicite.',
    'Un constructeur a-t-il un type de retour void ?',
    'Non : aucun type de retour, pas même void.',
    'Surcharge de constructeurs.',
    3),
  n('ch2-multi-ctors', '02 Classes & Objets', 'Plusieurs constructeurs',
    'Surcharge : signatures différentes pour différents cas.',
    'Relier aux besoins métier (étudiant avec/sans moyenne initiale).',
    'Comment Java choisit le constructeur ?',
    'Par le nombre et les types des arguments.',
    'this (hero).',
    2),
  n('ch2-this-hero', '02 Classes & Objets', 'Le mot-clé this',
    'this = référence à l’objet courant.',
    'Motiver le cas paramètre qui masque le champ (this.nom = nom).',
    'Pourquoi écrire this.nom = nom ?',
    'Pour distinguer le champ du paramètre homonyme.',
    'Simulateur this.',
    2),
  n('ch2-this', '02 Classes & Objets', 'this en pratique',
    'Ancrer this via l’interaction / simulateur.',
    'Faire reformuler : « this pointe vers moi-même ».',
    'this peut-il être null ?',
    'Non dans une instance method normale.',
    'Tableaux.',
    3),
  n('ch2-arrays', '02 Classes & Objets', 'Tableaux',
    'Tableau d’objets = tableau de références.',
    'Montrer new Etudiant[n] puis boucle d’initialisation.',
    'new Etudiant[3] crée-t-il 3 étudiants ?',
    'Non : 3 cases null jusqu’à new Etudiant() dans chaque case.',
    'Classe String.',
    3),
  n('ch2-string', '02 Classes & Objets', 'String',
    'String est une classe ; littéraux ; méthodes utiles.',
    'Préparer immutabilité et equals.',
    'String est-il un type primitif ?',
    'Non : c’est une classe (référence).',
    'Immutabilité.',
    3),
  n('ch2-string-immutable', '02 Classes & Objets', 'String immuable',
    'Toute « modification » crée une nouvelle String.',
    'Relier à la sécurité et au partage en mémoire.',
    's.toUpperCase() modifie-t-il s ?',
    'Non : retourne une nouvelle chaîne ; s inchangé si non réaffecté.',
    'equals vs ==.',
    2),
  n('ch2-equals', '02 Classes & Objets', 'equals vs ==',
    '== compare les références ; equals le contenu (pour String).',
    'Montrer le piège classique des littéraux / new String.',
    'Quand utiliser == avec des String ?',
    'Presque jamais pour le contenu ; préférer equals.',
    'Défi String.',
    3),
  n('ch2-string-challenge', '02 Classes & Objets', 'Défi String',
    'Faire prédire == / equals sur cas piège.',
    'Corriger collectivement.',
    'Deux new String("a") : equals ? == ?',
    'equals true ; == false (en général).',
    'StringBuilder.',
    2),
  n('ch2-stringbuilder', '02 Classes & Objets', 'StringBuilder',
    'Construction efficace de chaînes mutables.',
    'Cas d’usage : boucles de concaténation.',
    'Pourquoi StringBuilder plutôt que + en boucle ?',
    'Évite de créer plein d’objets String temporaires.',
    'Surcharge de méthodes.',
    3),
  n('ch2-overloading', '02 Classes & Objets', 'Surcharge (overloading)',
    'Même nom, signatures différentes — résolution à la compilation.',
    'Ne pas confondre avec overriding (héritage, plus tard).',
    'Peut-on surcharger seulement en changeant le type de retour ?',
    'Non.',
    'static (hero).',
    2),
  n('ch2-static-hero', '02 Classes & Objets', 'static — idée',
    'Membre de classe vs membre d’instance.',
    'Exemple : compteur d’objets, Math.sqrt.',
    'Faut-il un objet pour appeler une méthode static ?',
    'Non.',
    'Univers static.',
    2),
  n('ch2-static', '02 Classes & Objets', 'static en pratique',
    'Ancrer via visualisation / compteur partagé.',
    'Attention : trop de static = code procédural déguisé.',
    'Un champ static est-il partagé entre objets ?',
    'Oui.',
    'Passage de paramètres.',
    3),
  n('ch2-parameters', '02 Classes & Objets', 'Paramètres',
    'Passage par valeur des références (copie de la référence).',
    'Clarifier le mythe « Java passe les objets par référence ».',
    'Modifier p.x dans une méthode affecte-t-il l’appelant ?',
    'Oui si on mute l’objet ; non si on fait p = new ... dans la méthode.',
    'Packages.',
    3),
  n('ch2-packages', '02 Classes & Objets', 'Packages',
    'Organisation en espaces de noms ; import.',
    'Convention reverse-domain.',
    'À quoi sert package ?',
    'Structurer et éviter les collisions de noms.',
    'Projet pro / structure.',
    2),
  n('ch2-pro-project', '02 Classes & Objets', 'Structure de projet',
    'Montrer une organisation réaliste de dossiers/sources.',
    'Relier à ce que l’IDE attend.',
    'Où placer les sources Java typiquement ?',
    'src/main/java (Maven) ou src selon le projet pédagogique.',
    'private / encapsulation (hero).',
    2),
  n('ch2-private-hero', '02 Classes & Objets', 'Pourquoi private ?',
    'Protéger l’état ; contrôler les modifications.',
    'Reprendre BankAccount : balance public = danger.',
    'Que risque un attribut public balance ?',
    'Modification invalide (négatif, incohérent).',
    'Encapsulation.',
    2),
  n('ch2-encapsulation', '02 Classes & Objets', 'Encapsulation',
    'Cacher l’état + exposer un comportement sûr.',
    'Relier aux getters/setters avec validation.',
    'Encapsulation = seulement private ?',
    'Non : private + méthodes publiques bien conçues.',
    'Visibilité.',
    3),
  n('ch2-visibility', '02 Classes & Objets', 'Modificateurs de visibilité',
    'private, package, protected, public — intuition.',
    'Pour ce niveau : private par défaut pour les champs.',
    'Quel modificateur pour un champ d’état sensible ?',
    'private.',
    'Getters / setters.',
    2),
  n('ch2-getters-setters', '02 Classes & Objets', 'Getters et setters',
    'Accès contrôlé ; validation dans setX.',
    'Éviter les setters vides « pour la forme ».',
    'Un setter doit-il toujours accepter toute valeur ?',
    'Non : il peut refuser / corriger selon les règles métier.',
    'Bénéfice encapsulation.',
    2),
  n('ch2-encap-benefit', '02 Classes & Objets', 'Bénéfice de l’encapsulation',
    'Maintenabilité, invariants, évolution sans casser les clients.',
    'Exemple avant/après.',
    'Si je change la représentation interne, que se passe-t-il pour le client ?',
    'Rien si l’API publique reste stable.',
    'Synthèse campus HUD.',
    2),
  n('ch2-campus-hud', '02 Classes & Objets', 'Synthèse Campus',
    'Réviser classe/objet/état/comportement sur le thème campus.',
    'Interaction légère pour réactiver la salle.',
    'Citez une classe du campus et un attribut private.',
    'Ex. Etudiant / moyenne.',
    'Récap chapitre 02.',
    2),
  n('ch2-recap', '02 Classes & Objets', 'Récapitulatif chapitre 02',
    'Checklist mentale : classe, objet, new, this, String, static, encapsulation.',
    'Quiz oral 5 questions rapides.',
    'Différence clé classe / objet ?',
    'Modèle vs instance.',
    'Défi final.',
    3),
  n('ch2-final-challenge', '02 Classes & Objets', 'Défi final',
    'Mobiliser plusieurs notions sur un mini problème.',
    'Laisser chercher avant la correction ; autoriser l’IA puis exiger l’explication.',
    'Quelles classes voyez-vous dans l’énoncé ?',
    'Selon énoncé — justifier responsabilités.',
    'Corrigé / réponses.',
    5),
  n('ch2-final-answer', '02 Classes & Objets', 'Corrigé du défi final',
    'Corriger en explicitant le raisonnement, pas seulement le code.',
    'Relier chaque choix à une règle vue en cours.',
    'Pourquoi telle méthode n’est-elle pas static ?',
    'Parce qu’elle dépend de l’état de l’instance.',
    'Clôture du cours / perspectives.',
    3),
  n('end', 'Fin', 'Fin de la séance / du module',
    'Clôturer, rappeler ressources et travail à faire.',
    'Remercier ; annoncer la suite (héritage…) si prévu.',
    'Quelle idée gardez-vous pour la semaine ?',
    'Réponses libres — viser classe/objet ou encapsulation.',
    'Fin.',
    1),
]

/** Index rapide id → note */
export const NOTES_BY_ID: Record<string, SlideNoteEntry> = Object.fromEntries(
  ALL_SLIDE_NOTES.map(e => [e.id, e])
)

export function notesToMarkdown(entries: SlideNoteEntry[] = ALL_SLIDE_NOTES): string {
  const lines: string[] = [
    '# Notes enseignant — POO Java (Licence GLSI 2)',
    '',
    `Généré pour le cours interactif · ${entries.length} fiches (une par slide)`,
    '',
    '---',
    '',
  ]
  entries.forEach((e, i) => {
    const num = String(i + 1).padStart(2, '0')
    lines.push(`## Slide ${num} — ${e.title}`)
    lines.push('')
    lines.push(`- **ID :** \`${e.id}\``)
    lines.push(`- **Chapitre :** ${e.chapter}`)
    lines.push(`- **Durée estimée :** ≈ ${e.estimatedMinutes} min`)
    lines.push('')
    lines.push('### Objectif pédagogique')
    lines.push(e.teachingGoal)
    lines.push('')
    lines.push('### Notes de présentation')
    lines.push(e.speakerNotes)
    lines.push('')
    lines.push('### Question orale')
    lines.push(e.question)
    lines.push('')
    lines.push('### Réponse attendue')
    lines.push(e.expectedAnswer)
    lines.push('')
    lines.push('### Transition')
    lines.push(e.transition)
    lines.push('')
    lines.push('---')
    lines.push('')
  })
  return lines.join('\n')
}

export function noteToMarkdown(e: SlideNoteEntry, index: number): string {
  const num = String(index + 1).padStart(2, '0')
  return [
    `# Slide ${num} — ${e.title}`,
    '',
    `- **ID :** \`${e.id}\``,
    `- **Chapitre :** ${e.chapter}`,
    `- **Durée estimée :** ≈ ${e.estimatedMinutes} min`,
    '',
    '## Objectif pédagogique',
    e.teachingGoal,
    '',
    '## Notes de présentation',
    e.speakerNotes,
    '',
    '## Question orale',
    e.question,
    '',
    '## Réponse attendue',
    e.expectedAnswer,
    '',
    '## Transition',
    e.transition,
    '',
  ].join('\n')
}
